// ═══════════════════════════════════════════════════════════════════════════
// UCKG Semantic Schema — static Cypher bootstrap  (generated 2026-03-27T22:43:19.132594)
// Source : configt2c/semantic_schema_uckg_v3.json  version=v3
// Run in Neo4j Browser, cypher-shell, or as Docker init script.
// ═══════════════════════════════════════════════════════════════════════════

// ── 1. UCKGMeta_Schema singleton ─────────────────────────────────────────
MERGE (s:UCKGMeta_Schema {version: 'v3'}) SET s.notes = 'Carefully authored semantic schema for UCKG (v3). Every node, property, and relationship triple carries a precise semantic description, physical-name mapping, example values, and representative Cypher query patterns. This corpus is used by EnhancedT2CSSPipeline for semantic retrieval and is also persisted as a queryable metadata sub-graph inside Neo4j (UCKGMeta_* nodes).', s.embedding_corpus_size = 66, s.last_loaded = '2026-03-27T22:43:19.132594';

// ── 2. UCKGMeta_Node — one per entity type ────────────────────────────────
MERGE (n:UCKGMeta_Node {semantic: 'CVE'}) SET n.physical_label = 'UcoCVE', n.purpose = 'Represents a single Common Vulnerabilities and Exposures (CVE) disclosure entry. This is the canonical vulnerability identifier node. It stores CVSS scoring metadata and links to affected platforms (CPE) and observed real-world examples.', n.description = 'A CVE node identifies a specific publicly known vulnerability. Each node is uniquely identified by its \'label\' property (e.g. CVE-2021-44228). It carries CVSS v2/v3 scoring components such as base severity, exploitability subscore, impact subscore, and the raw vector string. The vulnerability status (ucovulnStatus) tracks whether NVD analysis is complete.', n.key_identifier = 'label', n.key_identifier_example = 'CVE-2021-44228', n.triggers = ['find CVE', 'vulnerability identifier', 'CVE score', 'severity rating', 'exploitability', 'impact score', 'CVSS vector', 'vulnerability status'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'CVE'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'Vulnerability'}) SET n.physical_label = 'UcoVulnerability', n.purpose = 'Represents the vulnerability concept node. It carries temporal metadata (published/modified dates) and a free-text summary. It links to its CVE identifier via hasCVE, and is linked from an ExploitTarget via hasVulnerability.', n.description = 'A Vulnerability node is the conceptual vulnerability record that wraps an NVD entry. It bridges ExploitTarget and CVE: ExploitTarget→Vulnerability→CVE→CPE. The key temporal properties are ucopublishedDateTime and ucolastModifiedDateTime. Note: date fields are stored here, NOT on UcoCVE.', n.key_identifier = 'uri', n.key_identifier_example = 'http://uckg.org/vulnerability/...', n.triggers = ['vulnerability published', 'disclosed in', 'vulnerability description', 'when was vulnerability found', 'vulnerability summary', 'modified date'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'Vulnerability'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'Weakness'}) SET n.physical_label = 'UcoCWE', n.purpose = 'Represents a Common Weakness Enumeration (CWE) entry — a class of software/hardware weakness. CWE nodes describe the abstract weakness category (e.g. CWE-79 Cross-Site Scripting). They link to observed real-world examples and are connected to exploit targets and CAPEC attack patterns.', n.description = 'A Weakness/CWE node is identified by its ucocweID property (e.g. CWE-79). It carries the weakness name (ucocweName), a summary, detailed description, exploitation likelihood, detection methods, potential mitigations text, and applicable platforms. The abstraction level (ucoabstraction) indicates whether this is a Variant, Base, Class, or Pillar in the CWE hierarchy.', n.key_identifier = 'ucocweID', n.key_identifier_example = 'CWE-79', n.triggers = ['weakness', 'CWE', 'software weakness', 'vulnerability class', 'cross-site scripting', 'buffer overflow', 'injection', 'weakness category', 'likelihood of exploit', 'weakness description'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'Weakness'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'ExploitTarget'}) SET n.physical_label = 'UcoExploitTarget', n.purpose = 'An abstract pivot node connecting a Weakness (CWE) and a Vulnerability. It represents the concept that a particular weakness is the underlying cause of a particular vulnerability.', n.description = 'ExploitTarget nodes act as intermediaries in the chain: CWE→ExploitTarget→Vulnerability→CVE→CPE. They have no descriptive properties themselves (only uri). To traverse from a CWE to its associated CVEs, you must go through ExploitTarget and then Vulnerability. ExploitTarget→Vulnerability uses UCOHASVULNERABILITY; ExploitTarget→Weakness uses UCOHASWEAKNESS.', n.key_identifier = 'uri', n.key_identifier_example = 'http://uckg.org/exploittarget/...', n.triggers = ['weakness causes vulnerability', 'CWE linked to CVE', 'exploit target', 'vulnerability root cause'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'ExploitTarget'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'Campaign'}) SET n.physical_label = 'UcoexCAMPAIGNS', n.purpose = 'Represents a MITRE ATT&CK Campaign — a coordinated set of malicious activities and behaviors conducted by a threat actor over a period of time with specific goals.', n.description = 'Campaign nodes describe named threat campaigns (e.g. Operation APT29). Each campaign can be attributed to one or more threat groups, and can use specific techniques and software. The name (ucoexNAME) is the primary identifier. The description (ucoexDESCRIPTION) contains detailed context.', n.key_identifier = 'ucoexNAME', n.key_identifier_example = 'Operation Wocao', n.triggers = ['campaign', 'operation', 'attack campaign', 'threat campaign', 'attributed to group', 'campaign uses', 'coordinated attack'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'Campaign'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'Group'}) SET n.physical_label = 'UcoexGROUPS', n.purpose = 'Represents a MITRE ATT&CK threat actor group (also called intrusion set or APT). Groups are named threat actors identified by security researchers, with known TTPs, tools, and campaign attributions.', n.description = 'Group nodes describe named threat actor groups (e.g. APT29, Lazarus Group, FIN7). A group can use techniques directly and employ software/tools. Campaigns can be attributed to groups. The name (ucoexNAME) is the primary identifier.', n.key_identifier = 'ucoexNAME', n.key_identifier_example = 'APT29', n.triggers = ['threat group', 'APT group', 'threat actor', 'hacker group', 'intrusion set', 'group uses', 'attributed to group', 'nation-state actor'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'Group'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'Technique'}) SET n.physical_label = 'UcoexMITREATTACK', n.purpose = 'Represents a MITRE ATT&CK technique or sub-technique describing a specific adversary behavior or method used to achieve a tactic objective.', n.description = 'Technique nodes cover both parent techniques (e.g. T1566 Phishing) and sub-techniques (e.g. T1566.001 Spearphishing Attachment). The name (ucoexNAME) typically contains the technique\'s descriptive name. The description (ucoexDESCRIPTION) explains the adversary behavior in detail. Techniques are the core pivot connecting groups, campaigns, software, mitigations, D3FEND controls, and CAPEC patterns.', n.key_identifier = 'ucoexNAME', n.key_identifier_example = 'Phishing', n.triggers = ['technique', 'ATT&CK technique', 'adversary behavior', 'attack technique', 'sub-technique', 'TTP', 'how do attackers', 'tactic technique'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'Technique'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'Tactic'}) SET n.physical_label = 'UcoexTACTICS', n.purpose = 'Represents a MITRE ATT&CK tactic — the adversary\'s high-level goal or phase in an attack (e.g. Initial Access, Execution, Persistence, Exfiltration).', n.description = 'Tactic nodes represent the 14 ATT&CK enterprise tactics (or ICS/mobile equivalents). Each tactic groups multiple techniques that share the same adversary objective. The name (ucoexNAME) is the tactic name. Note: in this KG, Tactic nodes are stored independently and are not directly linked to Technique nodes via explicit relationships — queries about \'techniques in a tactic\' require domain knowledge.', n.key_identifier = 'ucoexNAME', n.key_identifier_example = 'Initial Access', n.triggers = ['tactic', 'attack phase', 'adversary objective', 'kill chain phase', 'initial access', 'persistence', 'lateral movement', 'exfiltration', 'execution'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'Tactic'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'Software'}) SET n.physical_label = 'UcoexSOFTWARE', n.purpose = 'Represents software used by threat actors — including malware, tools, and commercial-off-the-shelf software weaponized by attackers. Sourced from MITRE ATT&CK Software entries.', n.description = 'Software nodes cover both malware (e.g. Emotet, Cobalt Strike) and tools (e.g. Mimikatz, PsExec). A software item can be used by multiple groups and campaigns, and can employ specific ATT&CK techniques. The name (ucoexNAME) is the primary identifier.', n.key_identifier = 'ucoexNAME', n.key_identifier_example = 'Mimikatz', n.triggers = ['software', 'malware', 'tool', 'ransomware', 'trojan', 'backdoor', 'exploit kit', 'remote access tool', 'RAT', 'software used by group'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'Software'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'Mitigation'}) SET n.physical_label = 'UcoexMITIGATIONS', n.purpose = 'Represents a MITRE ATT&CK mitigation — a security control or configuration recommendation that reduces the likelihood or impact of an adversary technique being successfully executed.', n.description = 'Mitigation nodes model the ATT&CK mitigation catalogue. Each mitigation is linked to one or more techniques it mitigates via the UCOEXMITIGATES relationship. The name (ucoexNAME) is the primary identifier (e.g. \'Multi-factor Authentication\', \'Network Segmentation\').', n.key_identifier = 'ucoexNAME', n.key_identifier_example = 'Multi-factor Authentication', n.triggers = ['mitigation', 'defense', 'countermeasure', 'control', 'remediation', 'how to prevent', 'how to mitigate', 'security recommendation', 'protect against'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'Mitigation'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'AttackPattern'}) SET n.physical_label = 'UcoexCAPEC', n.purpose = 'Represents a CAPEC (Common Attack Pattern Enumeration and Classification) entry — an abstract description of a common method used by adversaries to exploit software weaknesses.', n.description = 'AttackPattern nodes describe CAPEC attack patterns at varying abstraction levels (Meta, Standard, Detailed). Each CAPEC entry is identified by its ucoexCAPEC_id (e.g. CAPEC-66). It maps to related CWE weaknesses (UCOEXHASRELATEDWEAKNESS) and to ATT&CK techniques (UCOEXHASTAXONOMYMAPPING). CAPEC nodes carry rich context including prerequisites, execution flow, mitigations, severity, and likelihood.', n.key_identifier = 'ucoexCAPEC_id', n.key_identifier_example = 'CAPEC-66', n.triggers = ['attack pattern', 'CAPEC', 'common attack', 'how to exploit', 'attack method', 'exploitation technique', 'attack abstraction'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'AttackPattern'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'D3FENDControl'}) SET n.physical_label = 'UcoexMITRED3FEND', n.purpose = 'Represents a MITRE D3FEND defensive technique — a countermeasure that defends against one or more ATT&CK techniques. D3FEND complements ATT&CK by providing the defensive perspective.', n.description = 'D3FENDControl nodes model defensive techniques from the MITRE D3FEND knowledge base. Each control has a label (ucoexMITRED3FEND_LABEL) and a formal definition (ucoexMITRED3FEND_DEFINITION). They link to ATT&CK techniques via UCOEXHASMITREATTACK, meaning \'this D3FEND control covers/defends against this ATT&CK technique\'.', n.key_identifier = 'ucoexMITRED3FEND_LABEL', n.key_identifier_example = 'Network Traffic Filtering', n.triggers = ['D3FEND', 'defensive technique', 'defense control', 'countermeasure', 'how to defend', 'defensive measure', 'network defense'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'D3FENDControl'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'ObservedExample'}) SET n.physical_label = 'UcoexObservedExample', n.purpose = 'Represents a real-world observed example of a CWE weakness being exploited in practice. ObservedExample nodes link a textual description of the real exploitation event to the CVE where it was observed.', n.description = 'ObservedExample nodes are attached to CWE weakness nodes (via UCOHASOBSERVEDEXAMPLE) and link to the CVE where the example was observed (via UCOEXEXAMPLEOBSERVEDIN). This creates the full evidence chain: CWE → ObservedExample → CVE.', n.key_identifier = 'uri', n.key_identifier_example = 'http://uckg.org/observedexample/...', n.triggers = ['observed example', 'real world example', 'weakness in practice', 'CVE observed', 'exploitation example', 'CWE example'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'ObservedExample'}) MERGE (s)-[:META_HAS_NODE]->(n);

MERGE (n:UCKGMeta_Node {semantic: 'CPE'}) SET n.physical_label = 'UcoexCPE', n.purpose = 'Represents a CPE (Common Platform Enumeration) entry — a standardized naming scheme for IT systems, software, and packages. CPE nodes identify the specific platforms and products affected by a CVE.', n.description = 'CPE nodes are linked to CVE nodes via UCOEXHASCPE, meaning \'this CVE affects this CPE platform\'. The cpeName property holds the full CPE URI (e.g. cpe:/a:apache:log4j:2.14.1). The titles property provides human-readable platform names.', n.key_identifier = 'cpeName', n.key_identifier_example = 'cpe:/a:apache:log4j:2.14.1', n.triggers = ['affected platform', 'affected product', 'CPE', 'platform version', 'software version', 'product affected', 'vendor product'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (n:UCKGMeta_Node {semantic: 'CPE'}) MERGE (s)-[:META_HAS_NODE]->(n);

// ── 3. UCKGMeta_Property — one per property per entity type ───────────────
MERGE (p:UCKGMeta_Property {semantic: 'cveId', belongs_to: 'CVE'}) SET p.physical = 'label', p.type = 'string', p.description = 'The canonical CVE identifier string in the format CVE-YYYY-NNNNN. This is the primary lookup key for a CVE node.', p.example = 'CVE-2021-44228', p.query_pattern = 'MATCH (c:UcoCVE) WHERE c.label = \'CVE-2021-44228\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'cveId', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'baseSeverity', belongs_to: 'CVE'}) SET p.physical = 'ucobaseSeverity', p.type = 'string', p.description = 'CVSS base severity rating: CRITICAL, HIGH, MEDIUM, or LOW. Use this for severity-based filtering.', p.example = 'CRITICAL', p.query_pattern = 'MATCH (c:UcoCVE) WHERE c.ucobaseSeverity = \'CRITICAL\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'baseSeverity', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'exploitabilityScore', belongs_to: 'CVE'}) SET p.physical = 'ucoexploitabilityScore', p.type = 'string (numeric)', p.description = 'CVSS exploitability subscore as a string-encoded float (e.g. \'3.9\'). Reflects how easy it is to exploit the vulnerability.', p.example = '3.9', p.query_pattern = 'MATCH (c:UcoCVE) WHERE toFloat(c.ucoexploitabilityScore) > 3.0 RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'exploitabilityScore', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'impactScore', belongs_to: 'CVE'}) SET p.physical = 'ucoimpactScore', p.type = 'string (numeric)', p.description = 'CVSS impact subscore as a string-encoded float (e.g. \'5.9\'). Reflects the potential damage from a successful exploit.', p.example = '5.9', p.query_pattern = 'MATCH (c:UcoCVE) WHERE toFloat(c.ucoimpactScore) > 5.0 RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'impactScore', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'vectorString', belongs_to: 'CVE'}) SET p.physical = 'ucovectorString', p.type = 'string', p.description = 'CVSS vector string encoding all base metric values (e.g. AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H for Log4Shell).', p.example = 'AV:N/AC:L/PR:N/UI:N/S:C/C:H/I:H/A:H', p.query_pattern = 'MATCH (c:UcoCVE) WHERE c.ucovectorString CONTAINS \'AV:N\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'vectorString', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'vulnStatus', belongs_to: 'CVE'}) SET p.physical = 'ucovulnStatus', p.type = 'string', p.description = 'NVD analysis status of the CVE (e.g. Analyzed, Modified, Awaiting Analysis, Rejected). Reflects the completeness of NVD processing.', p.example = 'Analyzed', p.query_pattern = 'MATCH (c:UcoCVE) WHERE c.ucovulnStatus = \'Analyzed\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'vulnStatus', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'evaluatorSolution', belongs_to: 'CVE'}) SET p.physical = 'ucoevaluatorSolution', p.type = 'string', p.description = 'Free-text evaluator solution note added by NVD analysts. May describe workarounds or patch guidance.', p.example = 'Update to version 2.15.0 or later.', p.query_pattern = 'MATCH (c:UcoCVE) WHERE c.ucoevaluatorSolution IS NOT NULL RETURN c.label, c.ucoevaluatorSolution';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'evaluatorSolution', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'obtainAllPrivilege', belongs_to: 'CVE'}) SET p.physical = 'ucoobtainAllPrivilege', p.type = 'string (boolean)', p.description = 'CVSS v2 flag indicating whether exploitation yields full privilege escalation.', p.example = 'false', p.query_pattern = 'MATCH (c:UcoCVE) WHERE c.ucoobtainAllPrivilege = \'true\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'obtainAllPrivilege', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'userInteractionRequired', belongs_to: 'CVE'}) SET p.physical = 'ucouserInteractionRequired', p.type = 'string (boolean)', p.description = 'CVSS v2 flag indicating whether user interaction is required for exploitation.', p.example = 'false', p.query_pattern = 'MATCH (c:UcoCVE) WHERE c.ucouserInteractionRequired = \'false\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'userInteractionRequired', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'CVE'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this CVE node (internal knowledge graph identifier).', p.example = 'http://uckg.org/cve/CVE-2021-44228', p.query_pattern = 'MATCH (c:UcoCVE) WHERE c.uri CONTAINS \'CVE-2021-44228\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'CVE'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'CVE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'publishedDate', belongs_to: 'Vulnerability'}) SET p.physical = 'ucopublishedDateTime', p.type = 'datetime', p.description = 'The date and time when the vulnerability was first published in NVD. Use this for timeline/date-range queries.', p.example = '2021-12-10T10:15:00', p.query_pattern = 'MATCH (v:UcoVulnerability) WHERE v.ucopublishedDateTime >= datetime(\'2021-01-01\') RETURN v';
MATCH (n:UCKGMeta_Node {semantic: 'Vulnerability'}), (p:UCKGMeta_Property {semantic: 'publishedDate', belongs_to: 'Vulnerability'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'lastModifiedDate', belongs_to: 'Vulnerability'}) SET p.physical = 'ucolastModifiedDateTime', p.type = 'datetime', p.description = 'The date and time when the vulnerability record was last modified in NVD.', p.example = '2022-01-15T12:00:00', p.query_pattern = 'MATCH (v:UcoVulnerability) WHERE v.ucolastModifiedDateTime >= datetime(\'2022-01-01\') RETURN v';
MATCH (n:UCKGMeta_Node {semantic: 'Vulnerability'}), (p:UCKGMeta_Property {semantic: 'lastModifiedDate', belongs_to: 'Vulnerability'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'summary', belongs_to: 'Vulnerability'}) SET p.physical = 'ucosummary', p.type = 'string', p.description = 'Free-text description/summary of the vulnerability. Use this for keyword/text search queries.', p.example = 'Apache Log4j2 2.0-beta9 through 2.15.0 JNDI features used in ...', p.query_pattern = 'MATCH (v:UcoVulnerability) WHERE toLower(v.ucosummary) CONTAINS \'remote code execution\' RETURN v';
MATCH (n:UCKGMeta_Node {semantic: 'Vulnerability'}), (p:UCKGMeta_Property {semantic: 'summary', belongs_to: 'Vulnerability'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Vulnerability'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this Vulnerability node.', p.example = 'http://uckg.org/vulnerability/...', p.query_pattern = 'MATCH (v:UcoVulnerability) WHERE v.uri IS NOT NULL RETURN v.uri';
MATCH (n:UCKGMeta_Node {semantic: 'Vulnerability'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Vulnerability'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'cweId', belongs_to: 'Weakness'}) SET p.physical = 'ucocweID', p.type = 'string', p.description = 'The CWE identifier string (e.g. CWE-79). Primary lookup key for a weakness node.', p.example = 'CWE-79', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucocweID = \'CWE-79\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'cweId', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'cweName', belongs_to: 'Weakness'}) SET p.physical = 'ucocweName', p.type = 'string', p.description = 'Human-readable name of the weakness (e.g. \'Improper Neutralization of Input During Web Page Generation\').', p.example = 'Improper Neutralization of Input During Web Page Generation (Cross-site Scripting)', p.query_pattern = 'MATCH (w:UcoCWE) WHERE toLower(w.ucocweName) CONTAINS \'injection\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'cweName', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'summary', belongs_to: 'Weakness'}) SET p.physical = 'ucocweSummary', p.type = 'string', p.description = 'Short summary description of the weakness.', p.example = 'The software does not neutralize or incorrectly neutralizes user-controllable input before it is placed in output...', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucocweSummary IS NOT NULL RETURN w.ucocweID, w.ucocweSummary';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'summary', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Weakness'}) SET p.physical = 'ucodescription', p.type = 'string', p.description = 'Detailed description of the weakness from the CWE specification.', p.example = 'The product receives input from an upstream component...', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucodescription IS NOT NULL RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'abstraction', belongs_to: 'Weakness'}) SET p.physical = 'ucoabstraction', p.type = 'string', p.description = 'CWE abstraction level: Pillar, Class, Base, or Variant. Lower levels are more specific.', p.example = 'Base', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucoabstraction = \'Base\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'abstraction', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'likelihoodOfExploit', belongs_to: 'Weakness'}) SET p.physical = 'ucolikelihoodOfExploit', p.type = 'string', p.description = 'Estimated likelihood that this weakness will be exploited: High, Medium, or Low.', p.example = 'High', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucolikelihoodOfExploit = \'High\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'likelihoodOfExploit', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'status', belongs_to: 'Weakness'}) SET p.physical = 'ucostatus', p.type = 'string', p.description = 'CWE entry status (e.g. Draft, Stable, Incomplete, Deprecated).', p.example = 'Stable', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucostatus = \'Stable\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'status', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'applicablePlatform', belongs_to: 'Weakness'}) SET p.physical = 'ucoapplicablePlatform', p.type = 'string', p.description = 'Platforms/languages where this weakness applies (e.g. Language Independent, C, Java, PHP).', p.example = 'Language Independent', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucoapplicablePlatform CONTAINS \'PHP\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'applicablePlatform', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'commonConsequences', belongs_to: 'Weakness'}) SET p.physical = 'ucocommonConsequences', p.type = 'string', p.description = 'Description of the common consequences if this weakness is exploited.', p.example = 'Confidentiality, Integrity — Read/Modify application data', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucocommonConsequences CONTAINS \'Confidentiality\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'commonConsequences', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'potentialMitigations', belongs_to: 'Weakness'}) SET p.physical = 'ucopotentialMitigations', p.type = 'string', p.description = 'Free-text description of mitigations recommended by the CWE specification.', p.example = 'Use a vetted library or framework...', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucopotentialMitigations IS NOT NULL RETURN w.ucocweID, w.ucopotentialMitigations';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'potentialMitigations', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'detectionMethods', belongs_to: 'Weakness'}) SET p.physical = 'ucodetectionMethods', p.type = 'string', p.description = 'Recommended methods for detecting this weakness (e.g. Static Analysis, Fuzzing).', p.example = 'Static Analysis, Automated Testing', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucodetectionMethods CONTAINS \'Static Analysis\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'detectionMethods', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'extendedSummary', belongs_to: 'Weakness'}) SET p.physical = 'ucocweExtendedSummary', p.type = 'string', p.description = 'Extended summary providing additional context beyond the basic summary.', p.example = '...', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucocweExtendedSummary IS NOT NULL RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'extendedSummary', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'modesOfIntroduction', belongs_to: 'Weakness'}) SET p.physical = 'ucomodesOfIntroduction', p.type = 'string', p.description = 'When and how this weakness is typically introduced into software (e.g. Implementation, Design, Architecture).', p.example = 'Implementation', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucomodesOfIntroduction CONTAINS \'Implementation\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'modesOfIntroduction', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'structure', belongs_to: 'Weakness'}) SET p.physical = 'ucostructure', p.type = 'string', p.description = 'CWE structural nature (Simple, Composite, Chain).', p.example = 'Simple', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.ucostructure = \'Composite\' RETURN w';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'structure', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Weakness'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this CWE node.', p.example = 'http://uckg.org/cwe/CWE-79', p.query_pattern = 'MATCH (w:UcoCWE) WHERE w.uri IS NOT NULL RETURN w.uri';
MATCH (n:UCKGMeta_Node {semantic: 'Weakness'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Weakness'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'ExploitTarget'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI — the only property on ExploitTarget nodes.', p.example = 'http://uckg.org/exploittarget/...', p.query_pattern = 'MATCH (et:UcoExploitTarget) RETURN et.uri LIMIT 5';
MATCH (n:UCKGMeta_Node {semantic: 'ExploitTarget'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'ExploitTarget'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Campaign'}) SET p.physical = 'ucoexNAME', p.type = 'string', p.description = 'The name of the campaign (e.g. \'Operation Wocao\', \'FIN7\'). Primary lookup key.', p.example = 'Operation Wocao', p.query_pattern = 'MATCH (c:UcoexCAMPAIGNS) WHERE c.ucoexNAME = \'Operation Wocao\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'Campaign'}), (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Campaign'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Campaign'}) SET p.physical = 'ucoexDESCRIPTION', p.type = 'string', p.description = 'Detailed description of the campaign including goals, attribution, and timeline.', p.example = 'Operation Wocao was a cyber espionage campaign...', p.query_pattern = 'MATCH (c:UcoexCAMPAIGNS) WHERE toLower(c.ucoexDESCRIPTION) CONTAINS \'espionage\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'Campaign'}), (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Campaign'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Campaign'}) SET p.physical = 'ucoexDOMAIN', p.type = 'string', p.description = 'ATT&CK domain the campaign belongs to (e.g. enterprise-attack, ics-attack, mobile-attack).', p.example = 'enterprise-attack', p.query_pattern = 'MATCH (c:UcoexCAMPAIGNS) WHERE c.ucoexDOMAIN = \'enterprise-attack\' RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'Campaign'}), (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Campaign'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Campaign'}) SET p.physical = 'ucoexURL', p.type = 'string', p.description = 'Reference URL for this campaign on the MITRE ATT&CK website.', p.example = 'https://attack.mitre.org/campaigns/C0014/', p.query_pattern = 'MATCH (c:UcoexCAMPAIGNS) WHERE c.ucoexURL IS NOT NULL RETURN c.ucoexNAME, c.ucoexURL';
MATCH (n:UCKGMeta_Node {semantic: 'Campaign'}), (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Campaign'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Campaign'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this campaign node.', p.example = 'http://uckg.org/campaign/...', p.query_pattern = 'MATCH (c:UcoexCAMPAIGNS) WHERE c.uri IS NOT NULL RETURN c';
MATCH (n:UCKGMeta_Node {semantic: 'Campaign'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Campaign'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Group'}) SET p.physical = 'ucoexNAME', p.type = 'string', p.description = 'Name of the threat group (e.g. \'APT29\', \'Lazarus Group\'). Primary lookup key.', p.example = 'APT29', p.query_pattern = 'MATCH (g:UcoexGROUPS) WHERE g.ucoexNAME = \'APT29\' RETURN g';
MATCH (n:UCKGMeta_Node {semantic: 'Group'}), (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Group'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Group'}) SET p.physical = 'ucoexDESCRIPTION', p.type = 'string', p.description = 'Detailed description of the group including origin, motivation, and known activities.', p.example = 'APT29 is a threat group attributed to the Russian Foreign Intelligence Service...', p.query_pattern = 'MATCH (g:UcoexGROUPS) WHERE toLower(g.ucoexDESCRIPTION) CONTAINS \'russia\' RETURN g';
MATCH (n:UCKGMeta_Node {semantic: 'Group'}), (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Group'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Group'}) SET p.physical = 'ucoexDOMAIN', p.type = 'string', p.description = 'ATT&CK domain (e.g. enterprise-attack).', p.example = 'enterprise-attack', p.query_pattern = 'MATCH (g:UcoexGROUPS) WHERE g.ucoexDOMAIN = \'enterprise-attack\' RETURN g';
MATCH (n:UCKGMeta_Node {semantic: 'Group'}), (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Group'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Group'}) SET p.physical = 'ucoexURL', p.type = 'string', p.description = 'Reference URL on the MITRE ATT&CK website for this group.', p.example = 'https://attack.mitre.org/groups/G0016/', p.query_pattern = 'MATCH (g:UcoexGROUPS) WHERE g.ucoexURL IS NOT NULL RETURN g.ucoexNAME, g.ucoexURL';
MATCH (n:UCKGMeta_Node {semantic: 'Group'}), (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Group'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Group'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this group node.', p.example = 'http://uckg.org/group/...', p.query_pattern = 'MATCH (g:UcoexGROUPS) WHERE g.uri IS NOT NULL RETURN g';
MATCH (n:UCKGMeta_Node {semantic: 'Group'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Group'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Technique'}) SET p.physical = 'ucoexNAME', p.type = 'string', p.description = 'Technique name as it appears in ATT&CK (e.g. \'Phishing\', \'Valid Accounts\'). Primary lookup key.', p.example = 'Phishing', p.query_pattern = 'MATCH (t:UcoexMITREATTACK) WHERE toLower(t.ucoexNAME) CONTAINS \'phishing\' RETURN t';
MATCH (n:UCKGMeta_Node {semantic: 'Technique'}), (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Technique'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Technique'}) SET p.physical = 'ucoexDESCRIPTION', p.type = 'string', p.description = 'Detailed description of the adversary technique from MITRE ATT&CK.', p.example = 'Adversaries may send phishing messages to gain access to victim systems...', p.query_pattern = 'MATCH (t:UcoexMITREATTACK) WHERE toLower(t.ucoexDESCRIPTION) CONTAINS \'credential\' RETURN t';
MATCH (n:UCKGMeta_Node {semantic: 'Technique'}), (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Technique'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Technique'}) SET p.physical = 'ucoexDOMAIN', p.type = 'string', p.description = 'ATT&CK domain this technique belongs to (enterprise-attack, ics-attack, mobile-attack).', p.example = 'enterprise-attack', p.query_pattern = 'MATCH (t:UcoexMITREATTACK) WHERE t.ucoexDOMAIN = \'enterprise-attack\' RETURN t';
MATCH (n:UCKGMeta_Node {semantic: 'Technique'}), (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Technique'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Technique'}) SET p.physical = 'ucoexURL', p.type = 'string', p.description = 'Reference URL on the MITRE ATT&CK website for this technique.', p.example = 'https://attack.mitre.org/techniques/T1566/', p.query_pattern = 'MATCH (t:UcoexMITREATTACK) WHERE t.ucoexURL IS NOT NULL RETURN t.ucoexNAME, t.ucoexURL';
MATCH (n:UCKGMeta_Node {semantic: 'Technique'}), (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Technique'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Technique'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this technique node.', p.example = 'http://uckg.org/technique/...', p.query_pattern = 'MATCH (t:UcoexMITREATTACK) WHERE t.uri IS NOT NULL RETURN t';
MATCH (n:UCKGMeta_Node {semantic: 'Technique'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Technique'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Tactic'}) SET p.physical = 'ucoexNAME', p.type = 'string', p.description = 'Tactic name (e.g. \'Initial Access\', \'Persistence\', \'Lateral Movement\'). Primary lookup key.', p.example = 'Initial Access', p.query_pattern = 'MATCH (tac:UcoexTACTICS) WHERE tac.ucoexNAME = \'Initial Access\' RETURN tac';
MATCH (n:UCKGMeta_Node {semantic: 'Tactic'}), (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Tactic'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Tactic'}) SET p.physical = 'ucoexDESCRIPTION', p.type = 'string', p.description = 'Description of the tactic from MITRE ATT&CK.', p.example = 'The adversary is trying to get into your network...', p.query_pattern = 'MATCH (tac:UcoexTACTICS) WHERE tac.ucoexDESCRIPTION IS NOT NULL RETURN tac';
MATCH (n:UCKGMeta_Node {semantic: 'Tactic'}), (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Tactic'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Tactic'}) SET p.physical = 'ucoexDOMAIN', p.type = 'string', p.description = 'ATT&CK domain (enterprise-attack, ics-attack, mobile-attack).', p.example = 'enterprise-attack', p.query_pattern = 'MATCH (tac:UcoexTACTICS) WHERE tac.ucoexDOMAIN = \'enterprise-attack\' RETURN tac';
MATCH (n:UCKGMeta_Node {semantic: 'Tactic'}), (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Tactic'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Tactic'}) SET p.physical = 'ucoexURL', p.type = 'string', p.description = 'Reference URL on the MITRE ATT&CK website.', p.example = 'https://attack.mitre.org/tactics/TA0001/', p.query_pattern = 'MATCH (tac:UcoexTACTICS) WHERE tac.ucoexURL IS NOT NULL RETURN tac.ucoexNAME, tac.ucoexURL';
MATCH (n:UCKGMeta_Node {semantic: 'Tactic'}), (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Tactic'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Tactic'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this tactic node.', p.example = 'http://uckg.org/tactic/...', p.query_pattern = 'MATCH (tac:UcoexTACTICS) WHERE tac.uri IS NOT NULL RETURN tac';
MATCH (n:UCKGMeta_Node {semantic: 'Tactic'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Tactic'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Software'}) SET p.physical = 'ucoexNAME', p.type = 'string', p.description = 'Software name as listed in ATT&CK (e.g. \'Mimikatz\', \'Emotet\', \'Cobalt Strike\'). Primary lookup key.', p.example = 'Mimikatz', p.query_pattern = 'MATCH (s:UcoexSOFTWARE) WHERE s.ucoexNAME = \'Mimikatz\' RETURN s';
MATCH (n:UCKGMeta_Node {semantic: 'Software'}), (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Software'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Software'}) SET p.physical = 'ucoexDESCRIPTION', p.type = 'string', p.description = 'Detailed description of the software including its capabilities and typical use.', p.example = 'Mimikatz is a credential dumper capable of obtaining plaintext Windows account logins...', p.query_pattern = 'MATCH (s:UcoexSOFTWARE) WHERE toLower(s.ucoexDESCRIPTION) CONTAINS \'credential\' RETURN s';
MATCH (n:UCKGMeta_Node {semantic: 'Software'}), (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Software'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Software'}) SET p.physical = 'ucoexDOMAIN', p.type = 'string', p.description = 'ATT&CK domain this software belongs to.', p.example = 'enterprise-attack', p.query_pattern = 'MATCH (s:UcoexSOFTWARE) WHERE s.ucoexDOMAIN = \'enterprise-attack\' RETURN s';
MATCH (n:UCKGMeta_Node {semantic: 'Software'}), (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Software'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Software'}) SET p.physical = 'ucoexURL', p.type = 'string', p.description = 'Reference URL on the MITRE ATT&CK website.', p.example = 'https://attack.mitre.org/software/S0002/', p.query_pattern = 'MATCH (s:UcoexSOFTWARE) WHERE s.ucoexURL IS NOT NULL RETURN s.ucoexNAME, s.ucoexURL';
MATCH (n:UCKGMeta_Node {semantic: 'Software'}), (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Software'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Software'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this software node.', p.example = 'http://uckg.org/software/...', p.query_pattern = 'MATCH (s:UcoexSOFTWARE) WHERE s.uri IS NOT NULL RETURN s';
MATCH (n:UCKGMeta_Node {semantic: 'Software'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Software'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Mitigation'}) SET p.physical = 'ucoexNAME', p.type = 'string', p.description = 'Mitigation name from ATT&CK (e.g. \'Multi-factor Authentication\'). Primary lookup key.', p.example = 'Multi-factor Authentication', p.query_pattern = 'MATCH (m:UcoexMITIGATIONS) WHERE m.ucoexNAME = \'Multi-factor Authentication\' RETURN m';
MATCH (n:UCKGMeta_Node {semantic: 'Mitigation'}), (p:UCKGMeta_Property {semantic: 'name', belongs_to: 'Mitigation'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Mitigation'}) SET p.physical = 'ucoexDESCRIPTION', p.type = 'string', p.description = 'Description of the mitigation and how it reduces risk.', p.example = 'Use multi-factor authentication for user and privileged accounts...', p.query_pattern = 'MATCH (m:UcoexMITIGATIONS) WHERE m.ucoexDESCRIPTION IS NOT NULL RETURN m.ucoexNAME, m.ucoexDESCRIPTION';
MATCH (n:UCKGMeta_Node {semantic: 'Mitigation'}), (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'Mitigation'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Mitigation'}) SET p.physical = 'ucoexDOMAIN', p.type = 'string', p.description = 'ATT&CK domain (enterprise-attack, ics-attack, mobile-attack).', p.example = 'enterprise-attack', p.query_pattern = 'MATCH (m:UcoexMITIGATIONS) WHERE m.ucoexDOMAIN = \'enterprise-attack\' RETURN m';
MATCH (n:UCKGMeta_Node {semantic: 'Mitigation'}), (p:UCKGMeta_Property {semantic: 'domain', belongs_to: 'Mitigation'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Mitigation'}) SET p.physical = 'ucoexURL', p.type = 'string', p.description = 'Reference URL on the MITRE ATT&CK website.', p.example = 'https://attack.mitre.org/mitigations/M1032/', p.query_pattern = 'MATCH (m:UcoexMITIGATIONS) WHERE m.ucoexURL IS NOT NULL RETURN m.ucoexNAME, m.ucoexURL';
MATCH (n:UCKGMeta_Node {semantic: 'Mitigation'}), (p:UCKGMeta_Property {semantic: 'url', belongs_to: 'Mitigation'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Mitigation'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this mitigation node.', p.example = 'http://uckg.org/mitigation/...', p.query_pattern = 'MATCH (m:UcoexMITIGATIONS) WHERE m.uri IS NOT NULL RETURN m';
MATCH (n:UCKGMeta_Node {semantic: 'Mitigation'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'Mitigation'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'capecId', belongs_to: 'AttackPattern'}) SET p.physical = 'ucoexCAPEC_id', p.type = 'string', p.description = 'CAPEC identifier string (e.g. CAPEC-66). Primary lookup key.', p.example = 'CAPEC-66', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE ap.ucoexCAPEC_id = \'CAPEC-66\' RETURN ap';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'capecId', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'capecName', belongs_to: 'AttackPattern'}) SET p.physical = 'ucoexCAPEC_name', p.type = 'string', p.description = 'Human-readable name of the attack pattern (e.g. \'SQL Injection\').', p.example = 'SQL Injection', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE toLower(ap.ucoexCAPEC_name) CONTAINS \'injection\' RETURN ap';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'capecName', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'AttackPattern'}) SET p.physical = 'ucoexDescription', p.type = 'string', p.description = 'Detailed description of the attack pattern.', p.example = 'This attack exploits improper handling of input to a SQL database...', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE ap.ucoexDescription IS NOT NULL RETURN ap.ucoexCAPEC_id, ap.ucoexDescription';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'severity', belongs_to: 'AttackPattern'}) SET p.physical = 'ucoexSeverity', p.type = 'string', p.description = 'Severity rating of the attack pattern (High, Medium, Low).', p.example = 'High', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE ap.ucoexSeverity = \'High\' RETURN ap';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'severity', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'likelihood', belongs_to: 'AttackPattern'}) SET p.physical = 'ucoexLikelihood', p.type = 'string', p.description = 'Likelihood rating of the attack pattern being used (High, Medium, Low).', p.example = 'High', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE ap.ucoexLikelihood = \'High\' RETURN ap';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'likelihood', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'abstraction', belongs_to: 'AttackPattern'}) SET p.physical = 'ucoexAbstraction', p.type = 'string', p.description = 'CAPEC abstraction level: Meta, Standard, or Detailed.', p.example = 'Standard', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE ap.ucoexAbstraction = \'Standard\' RETURN ap';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'abstraction', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'consequences', belongs_to: 'AttackPattern'}) SET p.physical = 'ucoexConsequences', p.type = 'list<string>', p.description = 'List of potential consequences if this attack pattern is executed.', p.example = '[\'Data exfiltration\', \'Authentication bypass\']', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE any(c IN ap.ucoexConsequences WHERE toLower(c) CONTAINS \'bypass\') RETURN ap';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'consequences', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'prerequisites', belongs_to: 'AttackPattern'}) SET p.physical = 'ucoexPrerequisites', p.type = 'list<string>', p.description = 'List of prerequisites needed by an attacker to execute this attack pattern.', p.example = '[\'Network access to target\', \'Vulnerable input field\']', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE ap.ucoexPrerequisites IS NOT NULL RETURN ap.ucoexCAPEC_id, ap.ucoexPrerequisites';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'prerequisites', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'mitigations', belongs_to: 'AttackPattern'}) SET p.physical = 'ucoexMitigations', p.type = 'list<string>', p.description = 'List of recommended mitigations from the CAPEC specification.', p.example = '[\'Input validation\', \'Prepared statements\']', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE ap.ucoexMitigations IS NOT NULL RETURN ap.ucoexCAPEC_id, ap.ucoexMitigations';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'mitigations', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'AttackPattern'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this CAPEC node.', p.example = 'http://uckg.org/capec/CAPEC-66', p.query_pattern = 'MATCH (ap:UcoexCAPEC) WHERE ap.uri IS NOT NULL RETURN ap.uri';
MATCH (n:UCKGMeta_Node {semantic: 'AttackPattern'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'AttackPattern'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'label', belongs_to: 'D3FENDControl'}) SET p.physical = 'ucoexMITRED3FEND_LABEL', p.type = 'string', p.description = 'D3FEND defensive technique label/name. Primary lookup key.', p.example = 'Network Traffic Filtering', p.query_pattern = 'MATCH (d:UcoexMITRED3FEND) WHERE d.ucoexMITRED3FEND_LABEL = \'Network Traffic Filtering\' RETURN d';
MATCH (n:UCKGMeta_Node {semantic: 'D3FENDControl'}), (p:UCKGMeta_Property {semantic: 'label', belongs_to: 'D3FENDControl'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'definition', belongs_to: 'D3FENDControl'}) SET p.physical = 'ucoexMITRED3FEND_DEFINITION', p.type = 'string', p.description = 'Formal definition of the D3FEND defensive technique.', p.example = 'Restricting network traffic by filtering based on criteria such as IP address, port, or protocol...', p.query_pattern = 'MATCH (d:UcoexMITRED3FEND) WHERE d.ucoexMITRED3FEND_DEFINITION IS NOT NULL RETURN d.ucoexMITRED3FEND_LABEL, d.ucoexMITRED3FEND_DEFINITION';
MATCH (n:UCKGMeta_Node {semantic: 'D3FENDControl'}), (p:UCKGMeta_Property {semantic: 'definition', belongs_to: 'D3FENDControl'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'D3FENDControl'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this D3FEND control node.', p.example = 'http://uckg.org/d3fend/...', p.query_pattern = 'MATCH (d:UcoexMITRED3FEND) WHERE d.uri IS NOT NULL RETURN d';
MATCH (n:UCKGMeta_Node {semantic: 'D3FENDControl'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'D3FENDControl'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'ObservedExample'}) SET p.physical = 'ucoexDESCRIPTION', p.type = 'string', p.description = 'Description of the real-world exploitation event demonstrating the weakness.', p.example = 'XSS in the admin interface of Product X allows remote attackers to inject arbitrary web script...', p.query_pattern = 'MATCH (oe:UcoexObservedExample) WHERE toLower(oe.ucoexDESCRIPTION) CONTAINS \'xss\' RETURN oe';
MATCH (n:UCKGMeta_Node {semantic: 'ObservedExample'}), (p:UCKGMeta_Property {semantic: 'description', belongs_to: 'ObservedExample'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'ObservedExample'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this observed example node.', p.example = 'http://uckg.org/observedexample/...', p.query_pattern = 'MATCH (oe:UcoexObservedExample) WHERE oe.uri IS NOT NULL RETURN oe.uri';
MATCH (n:UCKGMeta_Node {semantic: 'ObservedExample'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'ObservedExample'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

MERGE (p:UCKGMeta_Property {semantic: 'cpeName', belongs_to: 'CPE'}) SET p.physical = 'cpeName', p.type = 'string', p.description = 'Full CPE URI string (e.g. cpe:/a:apache:log4j:2.14.1). The vendor, product, and version are encoded in the URI.', p.example = 'cpe:/a:apache:log4j:2.14.1', p.query_pattern = 'MATCH (cpe:UcoexCPE) WHERE cpe.cpeName CONTAINS \'apache:log4j\' RETURN cpe';
MATCH (n:UCKGMeta_Node {semantic: 'CPE'}), (p:UCKGMeta_Property {semantic: 'cpeName', belongs_to: 'CPE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'cpeNameId', belongs_to: 'CPE'}) SET p.physical = 'cpeNameId', p.type = 'string', p.description = 'Internal CPE dictionary identifier UUID.', p.example = '3fa85f64-5717-4562-b3fc-2c963f66afa6', p.query_pattern = 'MATCH (cpe:UcoexCPE) WHERE cpe.cpeNameId IS NOT NULL RETURN cpe.cpeName, cpe.cpeNameId';
MATCH (n:UCKGMeta_Node {semantic: 'CPE'}), (p:UCKGMeta_Property {semantic: 'cpeNameId', belongs_to: 'CPE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'titles', belongs_to: 'CPE'}) SET p.physical = 'titles', p.type = 'string', p.description = 'Human-readable title(s) for this CPE entry (e.g. \'Apache Log4j 2.14.1\').', p.example = 'Apache Log4j 2.14.1', p.query_pattern = 'MATCH (cpe:UcoexCPE) WHERE toLower(cpe.titles) CONTAINS \'apache\' RETURN cpe';
MATCH (n:UCKGMeta_Node {semantic: 'CPE'}), (p:UCKGMeta_Property {semantic: 'titles', belongs_to: 'CPE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'lastModified', belongs_to: 'CPE'}) SET p.physical = 'lastModified', p.type = 'datetime', p.description = 'Last modification timestamp of the CPE entry in the NVD dictionary.', p.example = '2022-03-15T10:00:00', p.query_pattern = 'MATCH (cpe:UcoexCPE) WHERE cpe.lastModified IS NOT NULL RETURN cpe.cpeName, cpe.lastModified';
MATCH (n:UCKGMeta_Node {semantic: 'CPE'}), (p:UCKGMeta_Property {semantic: 'lastModified', belongs_to: 'CPE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'dictionaryFound', belongs_to: 'CPE'}) SET p.physical = 'dictionary_found', p.type = 'boolean', p.description = 'Flag indicating whether this CPE was found in the NVD CPE dictionary.', p.example = 'True', p.query_pattern = 'MATCH (cpe:UcoexCPE) WHERE cpe.dictionary_found = true RETURN cpe';
MATCH (n:UCKGMeta_Node {semantic: 'CPE'}), (p:UCKGMeta_Property {semantic: 'dictionaryFound', belongs_to: 'CPE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);
MERGE (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'CPE'}) SET p.physical = 'uri', p.type = 'string', p.description = 'Canonical RDF/ontology URI for this CPE node.', p.example = 'http://uckg.org/cpe/...', p.query_pattern = 'MATCH (cpe:UcoexCPE) WHERE cpe.uri IS NOT NULL RETURN cpe';
MATCH (n:UCKGMeta_Node {semantic: 'CPE'}), (p:UCKGMeta_Property {semantic: 'uri', belongs_to: 'CPE'}) MERGE (n)-[:META_HAS_PROPERTY]->(p);

// ── 4. UCKGMeta_Relationship + META_CONNECTS_TO edges ────────────────────
MERGE (r:UCKGMeta_Relationship {semantic: 'hasCPE'}) SET r.physical_rel = 'UCOEXHASCPE', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Connects a CVE to the specific platform or product versions it affects. This is the primary relationship for \'which platforms/products are affected by this CVE\' queries.', r.traversal_direction = 'CVE → CPE', r.cypher_pattern = 'MATCH (c:UcoCVE)-[:UCOEXHASCPE]->(cpe:UcoexCPE)', r.triggers = ['affected platform', 'which CPE', 'platforms affected by CVE', 'products affected by vulnerability', 'vendor version affected'], r.example_query = 'MATCH (c:UcoCVE {label: \'CVE-2021-44228\'})-[:UCOEXHASCPE]->(cpe:UcoexCPE) RETURN cpe.cpeName';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'hasCPE'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'hasObservedExample'}) SET r.physical_rel = 'UCOHASOBSERVEDEXAMPLE', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Connects a CWE weakness to real-world observed examples of it being exploited. Enables finding historical evidence of a weakness being used in practice.', r.traversal_direction = 'Weakness (CWE) → ObservedExample', r.cypher_pattern = 'MATCH (w:UcoCWE)-[:UCOHASOBSERVEDEXAMPLE]->(oe:UcoexObservedExample)', r.triggers = ['real world examples of weakness', 'where has CWE been exploited', 'observed examples', 'historical exploitation of weakness'], r.example_query = 'MATCH (w:UcoCWE {ucocweID: \'CWE-79\'})-[:UCOHASOBSERVEDEXAMPLE]->(oe:UcoexObservedExample) RETURN oe.ucoexDESCRIPTION LIMIT 5';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'hasObservedExample'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'hasVulnerability'}) SET r.physical_rel = 'UCOHASVULNERABILITY', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Connects an ExploitTarget pivot node to its associated Vulnerability. Part of the CWE→ExploitTarget→Vulnerability→CVE chain. Required to traverse from weaknesses to vulnerability records.', r.traversal_direction = 'ExploitTarget → Vulnerability', r.cypher_pattern = 'MATCH (et:UcoExploitTarget)-[:UCOHASVULNERABILITY]->(v:UcoVulnerability)', r.triggers = ['vulnerability from weakness', 'exploit target linked vulnerability', 'CWE causes vulnerability'], r.example_query = 'MATCH (w:UcoCWE {ucocweID: \'CWE-89\'})<-[:UCOHASWEAKNESS]-(et:UcoExploitTarget)-[:UCOHASVULNERABILITY]->(v:UcoVulnerability)-[:UCOHASCVE_ID]->(c:UcoCVE) RETURN c.label LIMIT 10';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'hasVulnerability'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'hasWeakness'}) SET r.physical_rel = 'UCOHASWEAKNESS', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Connects an ExploitTarget pivot node to the underlying CWE weakness. Used to find which weakness class underlies a given vulnerability. Part of the full chain: CWE←ExploitTarget→Vulnerability→CVE.', r.traversal_direction = 'ExploitTarget → Weakness (CWE)', r.cypher_pattern = 'MATCH (et:UcoExploitTarget)-[:UCOHASWEAKNESS]->(w:UcoCWE)', r.triggers = ['weakness causing vulnerability', 'CWE for this CVE', 'underlying weakness', 'root cause weakness'], r.example_query = 'MATCH (v:UcoVulnerability)<-[:UCOHASVULNERABILITY]-(et:UcoExploitTarget)-[:UCOHASWEAKNESS]->(w:UcoCWE) MATCH (v)-[:UCOHASCVE_ID]->(c:UcoCVE {label: \'CVE-2021-44228\'}) RETURN w.ucocweID, w.ucocweName';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'hasWeakness'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'hasCVE'}) SET r.physical_rel = 'UCOHASCVE_ID', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Connects a Vulnerability concept node to its corresponding CVE identifier node. This is required to access CVE scoring data (baseSeverity, impactScore, etc.) from a Vulnerability node. Queries requiring both date and severity must traverse Vulnerability→CVE.', r.traversal_direction = 'Vulnerability → CVE', r.cypher_pattern = 'MATCH (v:UcoVulnerability)-[:UCOHASCVE_ID]->(c:UcoCVE)', r.triggers = ['CVE for vulnerability', 'vulnerability identifier', 'get CVE from vulnerability', 'link vulnerability to CVE'], r.example_query = 'MATCH (v:UcoVulnerability)-[:UCOHASCVE_ID]->(c:UcoCVE) WHERE v.ucopublishedDateTime >= datetime(\'2021-01-01\') RETURN c.label, c.ucobaseSeverity LIMIT 10';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'hasCVE'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'attributedTo'}) SET r.physical_rel = 'UCOEXATTRIBUTEDTO', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Indicates that a threat campaign has been attributed to (i.e. carried out by) a specific threat actor group. Use this to find which group is behind a campaign, or which campaigns a group has conducted.', r.traversal_direction = 'Campaign → Group', r.cypher_pattern = 'MATCH (camp:UcoexCAMPAIGNS)-[:UCOEXATTRIBUTEDTO]->(g:UcoexGROUPS)', r.triggers = ['campaign attributed to', 'who conducted campaign', 'which group is behind', 'threat actor responsible', 'campaign linked to group'], r.example_query = 'MATCH (camp:UcoexCAMPAIGNS)-[:UCOEXATTRIBUTEDTO]->(g:UcoexGROUPS) WHERE camp.ucoexNAME = \'Operation Wocao\' RETURN g.ucoexNAME';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'attributedTo'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'campaignUsesSoftware'}) SET r.physical_rel = 'UCOEXCAMPAIGNUSESSOFTWARE', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Indicates that a campaign used a specific software (malware/tool) as part of its operations. Use this to find tools deployed in a campaign, or which campaigns used a given tool.', r.traversal_direction = 'Campaign → Software', r.cypher_pattern = 'MATCH (camp:UcoexCAMPAIGNS)-[:UCOEXCAMPAIGNUSESSOFTWARE]->(s:UcoexSOFTWARE)', r.triggers = ['software used in campaign', 'malware deployed by campaign', 'tools used in operation', 'campaign used tool'], r.example_query = 'MATCH (camp:UcoexCAMPAIGNS {ucoexNAME: \'Operation Wocao\'})-[:UCOEXCAMPAIGNUSESSOFTWARE]->(s:UcoexSOFTWARE) RETURN s.ucoexNAME';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'campaignUsesSoftware'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'campaignUsesTechnique'}) SET r.physical_rel = 'UCOEXCAMPAIGNUSESTECHNIQUE', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Indicates that a campaign employed a specific ATT&CK technique. Use this to find techniques observed in a campaign, or which campaigns used a specific technique.', r.traversal_direction = 'Campaign → Technique', r.cypher_pattern = 'MATCH (camp:UcoexCAMPAIGNS)-[:UCOEXCAMPAIGNUSESTECHNIQUE]->(t:UcoexMITREATTACK)', r.triggers = ['technique used in campaign', 'campaign TTPs', 'attack techniques in operation', 'which campaigns use this technique'], r.example_query = 'MATCH (camp:UcoexCAMPAIGNS)-[:UCOEXCAMPAIGNUSESTECHNIQUE]->(t:UcoexMITREATTACK) WHERE camp.ucoexNAME = \'Operation Wocao\' RETURN t.ucoexNAME';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'campaignUsesTechnique'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'hasRelatedWeakness'}) SET r.physical_rel = 'UCOEXHASRELATEDWEAKNESS', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Maps a CAPEC attack pattern to the CWE weaknesses it exploits. Enables traversal between the CAPEC and CWE knowledge bases — finding which weaknesses enable a given attack pattern, or which attack patterns exploit a given weakness.', r.traversal_direction = 'AttackPattern (CAPEC) → Weakness (CWE)', r.cypher_pattern = 'MATCH (ap:UcoexCAPEC)-[:UCOEXHASRELATEDWEAKNESS]->(w:UcoCWE)', r.triggers = ['attack pattern for weakness', 'CAPEC exploits CWE', 'which attack patterns exploit this weakness', 'weakness related to CAPEC'], r.example_query = 'MATCH (ap:UcoexCAPEC)-[:UCOEXHASRELATEDWEAKNESS]->(w:UcoCWE {ucocweID: \'CWE-89\'}) RETURN ap.ucoexCAPEC_id, ap.ucoexCAPEC_name';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'hasRelatedWeakness'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'mapsToTechnique'}) SET r.physical_rel = 'UCOEXHASTAXONOMYMAPPING', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Maps a CAPEC attack pattern to corresponding ATT&CK techniques via ATT&CK\'s taxonomy mapping. This bridges the CAPEC and MITRE ATT&CK knowledge bases — allowing traversal from abstract attack patterns to concrete adversary behaviors.', r.traversal_direction = 'AttackPattern (CAPEC) → Technique (ATT&CK)', r.cypher_pattern = 'MATCH (ap:UcoexCAPEC)-[:UCOEXHASTAXONOMYMAPPING]->(t:UcoexMITREATTACK)', r.triggers = ['CAPEC maps to technique', 'attack pattern ATT&CK mapping', 'ATT&CK equivalent of CAPEC', 'technique for attack pattern'], r.example_query = 'MATCH (ap:UcoexCAPEC {ucoexCAPEC_id: \'CAPEC-66\'})-[:UCOEXHASTAXONOMYMAPPING]->(t:UcoexMITREATTACK) RETURN t.ucoexNAME';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'mapsToTechnique'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'groupUsesSoftware'}) SET r.physical_rel = 'UCOEXGROUPUSESSOFTWARE', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Indicates that a threat group uses a specific software (malware or tool). Use this to find tools associated with a group, or which groups use a given tool.', r.traversal_direction = 'Group → Software', r.cypher_pattern = 'MATCH (g:UcoexGROUPS)-[:UCOEXGROUPUSESSOFTWARE]->(s:UcoexSOFTWARE)', r.triggers = ['software used by group', 'malware used by APT', 'tools of threat actor', 'group\'s toolset', 'which groups use this malware'], r.example_query = 'MATCH (g:UcoexGROUPS {ucoexNAME: \'APT29\'})-[:UCOEXGROUPUSESSOFTWARE]->(s:UcoexSOFTWARE) RETURN s.ucoexNAME';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'groupUsesSoftware'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'groupUsesTechnique'}) SET r.physical_rel = 'UCOEXGROUPUSESTECHNIQUE', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Indicates that a threat group employs a specific ATT&CK technique. This is the primary relationship for threat-actor TTP queries (\'what techniques does APT29 use?\').', r.traversal_direction = 'Group → Technique', r.cypher_pattern = 'MATCH (g:UcoexGROUPS)-[:UCOEXGROUPUSESTECHNIQUE]->(t:UcoexMITREATTACK)', r.triggers = ['techniques used by group', 'group TTPs', 'APT uses technique', 'threat actor attack methods', 'which groups use this technique'], r.example_query = 'MATCH (g:UcoexGROUPS {ucoexNAME: \'APT29\'})-[:UCOEXGROUPUSESTECHNIQUE]->(t:UcoexMITREATTACK) RETURN t.ucoexNAME LIMIT 10';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'groupUsesTechnique'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'mitigates'}) SET r.physical_rel = 'UCOEXMITIGATES', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Indicates that a mitigation reduces the effectiveness of a specific ATT&CK technique. Use this to find how to defend against a technique, or which techniques a mitigation addresses.', r.traversal_direction = 'Mitigation → Technique', r.cypher_pattern = 'MATCH (m:UcoexMITIGATIONS)-[:UCOEXMITIGATES]->(t:UcoexMITREATTACK)', r.triggers = ['how to mitigate technique', 'defense against technique', 'which mitigations cover', 'countermeasure for attack'], r.example_query = 'MATCH (m:UcoexMITIGATIONS)-[:UCOEXMITIGATES]->(t:UcoexMITREATTACK) WHERE toLower(t.ucoexNAME) CONTAINS \'phishing\' RETURN m.ucoexNAME';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'mitigates'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'd3fendCoversTechnique'}) SET r.physical_rel = 'UCOEXHASMITREATTACK', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Maps a D3FEND defensive technique/control to the ATT&CK offensive technique it defends against. Enables querying \'what D3FEND controls cover this technique?\' or \'which ATT&CK techniques does this D3FEND control address?\'.', r.traversal_direction = 'D3FENDControl → Technique', r.cypher_pattern = 'MATCH (d:UcoexMITRED3FEND)-[:UCOEXHASMITREATTACK]->(t:UcoexMITREATTACK)', r.triggers = ['D3FEND control covers technique', 'defensive technique against ATT&CK', 'D3FEND defense for technique', 'which D3FEND defends against'], r.example_query = 'MATCH (d:UcoexMITRED3FEND)-[:UCOEXHASMITREATTACK]->(t:UcoexMITREATTACK) WHERE toLower(t.ucoexNAME) CONTAINS \'phishing\' RETURN d.ucoexMITRED3FEND_LABEL';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'd3fendCoversTechnique'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'exampleObservedIn'}) SET r.physical_rel = 'UCOEXEXAMPLEOBSERVEDIN', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Links a real-world observed example of a CWE weakness to the CVE identifier where that exploitation event was recorded. Completes the evidence chain: CWE → ObservedExample → CVE.', r.traversal_direction = 'ObservedExample → CVE', r.cypher_pattern = 'MATCH (oe:UcoexObservedExample)-[:UCOEXEXAMPLEOBSERVEDIN]->(c:UcoCVE)', r.triggers = ['example observed in CVE', 'weakness observed as CVE', 'real world CVE for weakness', 'exploitation evidence'], r.example_query = 'MATCH (w:UcoCWE {ucocweID: \'CWE-79\'})-[:UCOHASOBSERVEDEXAMPLE]->(oe:UcoexObservedExample)-[:UCOEXEXAMPLEOBSERVEDIN]->(c:UcoCVE) RETURN c.label, oe.ucoexDESCRIPTION LIMIT 5';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'exampleObservedIn'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

MERGE (r:UCKGMeta_Relationship {semantic: 'softwareUsesTechnique'}) SET r.physical_rel = 'UCOEXSOFTWAREUSESTECHNIQUE', r.domain_semantic = '', r.domain_physical = '', r.range_semantic = '', r.range_physical = '', r.description = 'Indicates that a software (malware or tool) employs a specific ATT&CK technique to achieve its goals. Use this to find techniques associated with a given tool, or which tools use a given technique.', r.traversal_direction = 'Software → Technique', r.cypher_pattern = 'MATCH (s:UcoexSOFTWARE)-[:UCOEXSOFTWAREUSESTECHNIQUE]->(t:UcoexMITREATTACK)', r.triggers = ['technique used by software', 'malware uses technique', 'tool\'s ATT&CK techniques', 'which tools use this technique'], r.example_query = 'MATCH (s:UcoexSOFTWARE {ucoexNAME: \'Mimikatz\'})-[:UCOEXSOFTWAREUSESTECHNIQUE]->(t:UcoexMITREATTACK) RETURN t.ucoexNAME';
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (r:UCKGMeta_Relationship {semantic: 'softwareUsesTechnique'}) MERGE (s)-[:META_HAS_RELATIONSHIP]->(r);

// ── 5. UCKGMeta_TraversalPath — documented multi-hop paths ───────────────
MERGE (tp:UCKGMeta_TraversalPath {name: 'CWE to CVE (full chain)'}) SET tp.description = 'Traverse from a weakness (CWE) to all CVEs that resulted from that weakness type.', tp.cypher_pattern = 'MATCH (w:UcoCWE)<-[:UCOHASWEAKNESS]-(et:UcoExploitTarget)-[:UCOHASVULNERABILITY]->(v:UcoVulnerability)-[:UCOHASCVE_ID]->(c:UcoCVE)', tp.use_cases = ['CVEs caused by SQL injection weakness', 'all CVEs for a given CWE'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (tp:UCKGMeta_TraversalPath {name: 'CWE to CVE (full chain)'}) MERGE (s)-[:META_HAS_PATH]->(tp);

MERGE (tp:UCKGMeta_TraversalPath {name: 'CVE to affected platforms'}) SET tp.description = 'Find all CPE platforms/products affected by a specific CVE.', tp.cypher_pattern = 'MATCH (c:UcoCVE)-[:UCOEXHASCPE]->(cpe:UcoexCPE)', tp.use_cases = ['which products are affected by Log4Shell', 'affected versions for a CVE'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (tp:UCKGMeta_TraversalPath {name: 'CVE to affected platforms'}) MERGE (s)-[:META_HAS_PATH]->(tp);

MERGE (tp:UCKGMeta_TraversalPath {name: 'CVE to weakness (reverse)'}) SET tp.description = 'From a CVE, find the underlying CWE weakness via the exploit target chain.', tp.cypher_pattern = 'MATCH (c:UcoCVE)<-[:UCOHASCVE_ID]-(v:UcoVulnerability)<-[:UCOHASVULNERABILITY]-(et:UcoExploitTarget)-[:UCOHASWEAKNESS]->(w:UcoCWE)', tp.use_cases = ['what weakness type underlies CVE-XXXX', 'CWE for a specific CVE'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (tp:UCKGMeta_TraversalPath {name: 'CVE to weakness (reverse)'}) MERGE (s)-[:META_HAS_PATH]->(tp);

MERGE (tp:UCKGMeta_TraversalPath {name: 'CWE to ATT&CK techniques (via CAPEC)'}) SET tp.description = 'From a CWE weakness, find related ATT&CK techniques through CAPEC attack patterns.', tp.cypher_pattern = 'MATCH (w:UcoCWE)<-[:UCOEXHASRELATEDWEAKNESS]-(ap:UcoexCAPEC)-[:UCOEXHASTAXONOMYMAPPING]->(t:UcoexMITREATTACK)', tp.use_cases = ['ATT&CK techniques for SQL injection weakness', 'technique coverage for a CWE'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (tp:UCKGMeta_TraversalPath {name: 'CWE to ATT&CK techniques (via CAPEC)'}) MERGE (s)-[:META_HAS_PATH]->(tp);

MERGE (tp:UCKGMeta_TraversalPath {name: 'Group full TTP profile'}) SET tp.description = 'Retrieve the complete TTP profile of a threat group: techniques, software, and campaigns.', tp.cypher_pattern = 'MATCH (g:UcoexGROUPS) OPTIONAL MATCH (g)-[:UCOEXGROUPUSESTECHNIQUE]->(t:UcoexMITREATTACK) OPTIONAL MATCH (g)-[:UCOEXGROUPUSESSOFTWARE]->(s:UcoexSOFTWARE) OPTIONAL MATCH (camp:UcoexCAMPAIGNS)-[:UCOEXATTRIBUTEDTO]->(g)', tp.use_cases = ['complete profile of APT29', 'all TTPs for a threat actor'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (tp:UCKGMeta_TraversalPath {name: 'Group full TTP profile'}) MERGE (s)-[:META_HAS_PATH]->(tp);

MERGE (tp:UCKGMeta_TraversalPath {name: 'Technique to mitigations and D3FEND'}) SET tp.description = 'For a given ATT&CK technique, find all mitigations and D3FEND controls that address it.', tp.cypher_pattern = 'MATCH (t:UcoexMITREATTACK) OPTIONAL MATCH (m:UcoexMITIGATIONS)-[:UCOEXMITIGATES]->(t) OPTIONAL MATCH (d:UcoexMITRED3FEND)-[:UCOEXHASMITREATTACK]->(t)', tp.use_cases = ['how to defend against phishing', 'mitigations for credential dumping'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (tp:UCKGMeta_TraversalPath {name: 'Technique to mitigations and D3FEND'}) MERGE (s)-[:META_HAS_PATH]->(tp);

MERGE (tp:UCKGMeta_TraversalPath {name: 'CWE observed examples to CVE evidence'}) SET tp.description = 'Find real-world CVEs where a specific CWE was demonstrated.', tp.cypher_pattern = 'MATCH (w:UcoCWE)-[:UCOHASOBSERVEDEXAMPLE]->(oe:UcoexObservedExample)-[:UCOEXEXAMPLEOBSERVEDIN]->(c:UcoCVE)', tp.use_cases = ['real CVEs for XSS weakness', 'historical exploitation of CWE-89'];
MATCH (s:UCKGMeta_Schema {version: 'v3'}), (tp:UCKGMeta_TraversalPath {name: 'CWE observed examples to CVE evidence'}) MERGE (s)-[:META_HAS_PATH]->(tp);

// ── Verification query ────────────────────────────────────────────────────
MATCH (n:UCKGMeta_Node)
OPTIONAL MATCH (n)-[:META_HAS_PROPERTY]->(p:UCKGMeta_Property)
RETURN n.semantic AS node, n.physical_label AS label,
       count(p) AS properties
ORDER BY n.semantic;
